# Generated by Django 5.2.13 on 2026-04-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_merchant_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
