# Generated by Django 5.2.14 on 2026-06-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='memo',
        ),
    ]
